### ISSUE TITLE
No geoip In the latest build

### ISSUE THREAD

**Issue by fi6** [v2fly/docker#2]
When using geoip in conf file, the following error is shown:
v2ray_1  | V2Ray v4.22.1-124-g13b309f1 (v4.22.1-124-g13b309f1) docker-fly-amd64 (go1.13.9 linux/amd64)
v2ray_1  | A unified platform for anti-censorship.
v2ray_1  | main: failed to read config files: [/etc/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl:
v2ray_1  | v2ctl> Read config:  /etc/v2ray/config.json
v2ray_1  | v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: can't skip unknown wire type 7 > exit status 255

And when I change back to v4.22.1, everything works fine.

I've tried to add geoip into /usr/local by setting -v in the docker run command, but it doesn't work.

**Comment by junjieyuan** [comment]
It can be reproduced in version 4.23.1.

**Comment by junjieyuan** [comment]
fixed

SHA1(d53c43f617e74a4305df225038f9f6a45e84bc12)
