### ISSUE TITLE
unnamed volume

### ISSUE THREAD

**Issue by r2007** [v2fly/docker#33]
每次docker-compose up -d && docker-compose down会产生一个随机volume

# docker-compose.yml

version: '3.8'
services:
  proxy:
    image: v2fly/v2fly-core
    volumes:
      - ./config/client.json:/etc/v2ray/config.json:ro
    ports:
      - "127.0.0.1:10800:10800"

**Comment by kslr** [comment]
https://docs.docker.com/compose/reference/down/

**Comment by r2007** [comment]
发现去掉就没问题，为啥不在dockfile里面去掉volume那一行？意义是什么？
