### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by yjiangnan** [v2fly/docker#40]
I get the following error message:
```
$ docker logs v2ray
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
main: failed to create server > v2ray.com/core/app/log: failed to initialize access logger > open /var/folders/bk/5d1vvhsn1h7fjv4_blhxvpgm0000gn/T/cenmrev.v2rayx.log/access.log: no such file or directory
```

**Comment by SkyperTHC** [comment]
The examples from the original v2ray docker image dont work and throw errors. Instead I manage to start it like this:


example config.json located to `v2ray/config.json`

```
docker run  --rm --name v2ray -v $(pwd)/v2ray:/etc/v2ray -p 10086:10086 v2fly/v2fly-core
```

Someone should really update the examples as they no longer work.....

**Comment by kslr** [comment]
[efaa50e520cc4f27331ed1624ef593c7a45722c2](https://github.com/v2fly/docker/commit/efaa50e520cc4f27331ed1624ef593c7a45722c2)
https://github.com/v2fly/docker/commit/2e80d3583d5bf8ebbfe9a31cb73ebbf02d60244d
