### ISSUE TITLE
v2fly v5 support

### ISSUE THREAD

**Issue by veekxt** [v2fly/docker#41]
v2fly v5 support

**Comment by lostmaniac** [comment]
+1

**Comment by CXwudi** [comment]
+1

**Comment by kslr** [comment]
Pr welcome

**Comment by CXwudi** [comment]
Based on my understanding. There is no PR needed. Simply just manually trigger the GitHub CI and that's all, but this can only be done by the repo maintainers

**Comment by CXwudi** [comment]
For anyone who can't wait, I found this: https://hub.docker.com/r/teddysun/v2ray

It is the same guy who maintained the docker version of xray

**Comment by kslr** [comment]
> Based on my understanding. There is no PR needed. Simply just manually trigger the GitHub CI and that's all, but this can only be done by the repo maintainers

Pushed

**Comment by chisaato** [comment]
Also, need to update starup CMD 
https://github.com/v2fly/docker/blob/68bada24e25965b910ac9568c265e11110e18938/Dockerfile#L15

**Comment by kslr** [comment]
> Also, need to update starup CMD
> 
> https://github.com/v2fly/docker/blob/68bada24e25965b910ac9568c265e11110e18938/Dockerfile#L15

pushed

**Comment by Dznan** [comment]
> > Also, need to update starup CMD
> > https://github.com/v2fly/docker/blob/68bada24e25965b910ac9568c265e11110e18938/Dockerfile#L15
> 
> pushed

I think it would be better if make `/usr/bin/v2ray` as entrypoint. When we use `docker run` with different parameters, we don't need to add `/usr/bin/v2ray`.

**Comment by kslr** [comment]
[2e80d3583d5bf8ebbfe9a31cb73ebbf02d60244d](https://github.com/v2fly/docker/commit/2e80d3583d5bf8ebbfe9a31cb73ebbf02d60244d)
https://github.com/v2fly/docker/commit/efaa50e520cc4f27331ed1624ef593c7a45722c2
