### ISSUE TITLE
怎样修改 etc/systemd/system/v2ray.service

### ISSUE THREAD

**Issue by ynhj123** [v2fly/docker#42]
我想在docker部署的v2fly-core中添加配置Environment="V2RAY_VMESS_AEAD_FORCED=false"，但是找不到该文件

**Comment by kslr** [comment]
see https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by cloudwindy** [comment]
Please use English to describe your problem.

**Comment by ynhj123** [comment]
@kslr Thanks for your help, I added "-e V2RAY_VMESS_AEAD_FORCED=false"
