### ISSUE TITLE
the latest container build is with security vulnerabilities

### ISSUE THREAD

**Issue by robertwenquan** [v2fly/docker#61]
The current latest image of v2fly-core is with plenty of security vulnerabilities, on alpine 3.17.1, and v2ray 5.2.1.

![image](https://github.com/v2fly/docker/assets/8893623/c69cf993-b6b3-4079-915b-35ec80f9d75e)

upgrading to alpine 3.18 and v2ray 5.4.1 would clear up the vulnerabilities

![image](https://github.com/v2fly/docker/assets/8893623/0654ba2d-d738-47c7-b3a9-69c2cd966024)

As in this repo, it's just using the "latest" tag to build the image, pls help retrigger the build in some way to make the latest image up to date.

Thanks!

**Comment by kslr** [comment]
thanks,  [updated](https://github.com/v2fly/docker/actions/runs/4986919111/jobs/8928192643)
