### ISSUE TITLE
Please run Action to push the latest docker image to Docker Hub.

### ISSUE THREAD

**Issue by anyshpm** [v2fly/docker#76]
RT.

**Comment by kslr** [comment]
pushed

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Please re-run action for new latest again

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Need re-run for missing [v5.23.0](https://github.com/v2fly/v2ray-core/releases/tag/v5.23.0)

**Comment by kslr** [comment]
added, p.s here is a faster update https://github.com/v2fly/v2ray-core/pkgs/container/v2ray
